# Generated by Django 3.1.4 on 2020-12-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=2),
        ),
    ]
